name: 'ntd - line replace utils'
description: 'ntd - line replace utils'
inputs:
  input_file:
    description: Input file
    required: true
  line_pattern:
    description: RegEx pattern to detect the line to be replaced
    required: true
  replace_value:
    description: Replace value
    required: false
    default: ""
  replace_file:
    description: Replace file
    required: false
    default: "blank.txt"
outputs:
  replaced_string: 
    description: The replaced content of the file
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_FILE: ${{ inputs.input_file }}
    LINE_PATTERN: ${{ inputs.line_pattern }}
    REPLACE_VALUE: ${{ inputs.replace_value }}
    REPLACE_FILE: ${{ inputs.replace_file }}
branding:
  icon: arrow-up-circle
  color: blue
